<?php if (!$authorized): ?>
<script type="text/javascript">
    $(document).ready(function()
        {
            bootbox.confirm({ title: "Enter login and password to acces files list:",
                message: '<form id="loginForm" method="post" action="<?=$this->url('list'); ?>">\
                            <input type="text" name="user" class="bootbox-input bootbox-input-password form-control" autocomplete="off" placeholder="Login" /><br/>\
                            <input type="password" name="password" class="bootbox-input bootbox-input-password form-control" placeholder="Password" />\
                        </form>',
                callback: function(result)
                {
                    if(result)
                        $('#loginForm').submit();
                }
            });
    );
</script>
    <h2>Authorization required</h2>
<?php else: ?>

<h2>Files list</h2>

<?php if(count($files) == 0): ?>

    <p>
        <i>No files uploaded yet</i>
    </p>

<?php else: ?>
    <script type="text/javascript">
        $(document).ready(function()
        {
            $('.glyphicon-remove').each(function()
            {
                $(this).click(function ()
                {
                    var element = this;

                    bootbox.confirm({
                        message: "Are you sure wanna delete " + $(element).data('name') + "?",
                        buttons: {
                            confirm: {
                                label: 'Sure',
                                className: 'btn-success'
                            },
                            cancel: {
                                label: 'Nope',
                                className: 'btn-danger'
                            }
                        },
                        callback: function (result)
                        {
                            if (result)
                            {
                                var row = $(element).closest('tr');
                                $(row).addClass('toDeleteRow')

                                $(element).attr('class', 'glyphicon glyphicon-hourglass').off('click');

                                $.get(
                                    '<?=$this->url('upload',['action'=>'delete']); ?>',
                                    { id: $(element).data('id') },
                                    function (response)
                                    {
                                        if (response.success)
                                        {
                                            $(row).delay(300).remove();
                                        }
                                        else
                                        {
                                            $(element).attr('class', 'glyphicon glyphicon-flash');
                                            $(row).attr('class', 'brokenRow');

                                            bootbox.alert({
                                                message: "Unable to delete " + $(element).data('name'),
                                                size: 'small'
                                            });
                                        }
                                    }, 'json');
                            }
                        }
                    });
                });
            });
         });
    </script>
    <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th></th>
                <th>ID</th>
                <th>Name</th>
                <th>Size</th>
                <th>Type</th>
                <th>Date</th>
                <th>Downloaded</th>
            </tr>
            </thead>
            <tbody>

        <?php foreach($files as $file): ?>
            <tr>
                <td><span data-id="<?=$file->id?>" data-name="<?=$file->name?>" class="glyphicon glyphicon-remove"></span></td>
                <td><?=$file->id ?></td>
                <td><a href="/<?=$file->id?>"><?=$file->name ?></a>
                    <?php if ($file->password): ?>
                        <span class="glyphicon glyphicon-lock"></span>
                    <?php endif; ?>
                </td>
                <td><?=number_format(($file->size) /pow(1024, 2), 2) ?>MB</td>
                <td><?=$file->type ?></td>
                <td><?=$file->uploaded ?></td>
                <td class="text-center"><?=$file->downloaded ?></td>
            </tr>
        <?php endforeach;?>
                </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>