<h1>Upload files</h1>
<?php
    $form = $this->form;

    $form->prepare();

    $form->get('password')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Any password'
    ]);

    $form->get('file')->setAttributes([
        'class'=>'form-control',
    ]);

    $form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

?>
    <div class="row">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('file')); ?>
    <?= $this->formElement($form->get('file')); ?>
    <?= $this->formElementErrors($form->get('file')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('password')); ?>
    <?= $this->formElement($form->get('password')); ?>
    <?= $this->formElementErrors($form->get('password')); ?>
</div>

<?= $this->formElement($form->get('submit')); ?>

<?= $this->form()->closeTag(); ?>
</div>
</div>